import type { Metadata } from "next";
import "./globals.css";
import { TaskListsProvider } from "@/contexts/TaskListsContext";
import { UserContextProvider } from "@/contexts/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TaskListsProvider>
          <UserContextProvider>
            {children}
          </UserContextProvider>
        </TaskListsProvider>
      </body>
    </html>
  );
}
