import type { Metadata } from "next";
import "./globals.css";
import { TaskListsProvider } from "@/contexts/TaskListsContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TaskListsProvider>
          {children}
        </TaskListsProvider>
      </body>
    </html>
  );
}
